For review only
IPv18/NOCD pull request #8
Opened 2023-04-11 17:40 UTC by OsamaMomani

2023-04-12 21:19 UTC, o54ma-4l5h4r1f requested changes

2023-04-12 21:19 UTC, o54ma-4l5h4r1f commented on src/network_sniffer/network_sniffer.py
There is a module in python I found useful called `psutil`, It can retrieve information on running processes and system utilization (CPU, memory, disks, network, sensors).

It implements many functionalities offered by classic UNIX command line tools such as `ps`, `top`, `iotop`, `lsof`, `netstat`, `ifconfig`, `free` and others.

And the cool thing it supports the following platforms:
- Linux
- Windows
- macOS
- FreeBSD, OpenBSD, NetBSD
- Sun Solaris
- AIX


Here is a sample code :

```python
import psutil

class psutilHelper():
    def __init__(self):
        self.table = []
        self.update_table()

    def update_table(self):
        self.table = []
        # get a list of all running processes
        pids = psutil.pids()
        # iterate over the processes and print their network connections (i.e. TCP connections)
        for pid in pids:
            p = psutil.Process(pid)

            if p.connections(kind='tcp'):
                self.table += [p.as_dict()]
                
    def debug(self):
        for E in self.table:
            print(
                "user\t: ", E["username"], 
                "\nname\t: ", E["name"], 
                "\nexe\t: ", E["exe"], 
                "\ncwd\t: ", E["cwd"], 
                "\ncount\t: ", E["io_counters"],
                "\nconn\t: ", E["connections"], 
                "\n\n  * ", E["connections"][0].laddr + E["connections"][0].raddr,  
                "\n\nstat\t: ", E["connections"][0].status, 
                '\n------------------------------------------------------------\n'
            ) # and so many other things ^^ 
        
def main():
    ps = psutilHelper()
    ps.debug()
    
if __name__ == "__main__":
    main()
```

2023-04-12 22:10 UTC, OsamaMomani commented on src/network_sniffer/network_sniffer.py
Indeed `psutil` seems better in some ways; it is cross-platform and provides more utilities. However, I have some concerns regarding the performance.  
We update the socket table for every new packet sniffed so performance matters here.

We can run a simple test using `/usr/bin/time -v ` of two files initializing psuitlHelper and sshelper. 

```
        Command being timed: "sudo python3 psuitlHelper.py"
        User time (seconds): 0.29
        System time (seconds): 0.14
        Percent of CPU this job got: 97%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.44
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 29832
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 9290
        Voluntary context switches: 23
        Involuntary context switches: 21
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
```
        Command being timed: "sudo python3 sshelper.py"
        User time (seconds): 0.04
        System time (seconds): 0.02
        Percent of CPU this job got: 98%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.06
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 9476
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 3229
        Voluntary context switches: 39
        Involuntary context switches: 18
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

sshelper is ~7x faster (Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.06), 
takes 3x time less memory (Maximum resident set size (kbytes): 9476)

2023-04-13 00:53 UTC, o54ma-4l5h4r1f commented on src/network_sniffer/network_sniffer.py
Good point, but it was just a demo to show you the tool capabilities.

You can just get rid of `p.as_dict()` which returns a huge amount of data as shown below : 

```python
import psutil
import json

pids = psutil.pids()
p = psutil.Process(pids[-1])
print(json.dumps(p.as_dict()))
```
```json
{"memory_info": [14581760, 28008448, 8425472, 2711552, 0, 6483968, 0], "gids": [1000, 1000, 1000], "memory_maps": [["/usr/bin/python3.8", 3821568, 5496832, 841728, 3510272, 0, 32768, 278528, 3821568, 278528, 0], ["[anon]", 4231168, 4481024, 4231168, 0, 0, 0, 4231168, 4231168, 4231168, 0], ["[heap]", 1331200, 1445888, 1331200, 0, 0, 0, 1331200, 1331200, 1331200, 0], ["/usr/lib/x86_64-linux-gnu/liblzma.so.5.2.4", 86016, 167936, 9216, 77824, 0, 0, 8192, 86016, 8192, 0], ["/usr/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so", 81920, 81920, 31744, 73728, 0, 0, 8192, 81920, 8192, 0], ["/usr/lib/python3.8/lib-dynload/resource.cpython-38-x86_64-linux-gnu.so", 24576, 24576, 16384, 16384, 0, 0, 8192, 24576, 8192, 0], ["/home/o54ma/.local/lib/python3.8/site-packages/psutil/_psutil_posix.cpython-38-x86_64-linux-gnu.so", 24576, 24576, 24576, 0, 0, 16384, 8192, 24576, 8192, 0], ["/home/o54ma/.local/lib/python3.8/site-packages/psutil/_psutil_linux.cpython-38-x86_64-linux-gnu.so", 28672, 28672, 28672, 0, 0, 20480, 8192, 28672, 8192, 0], ["/usr/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so", 49152, 49152, 18432, 40960, 0, 0, 8192, 49152, 8192, 0], ["/usr/lib/locale/locale-archive", 442368, 5705728, 6144, 442368, 0, 0, 0, 442368, 0, 0], ["/usr/lib/x86_64-linux-gnu/libbsd.so.0.10.0", 86016, 102400, 8192, 77824, 0, 0, 8192, 86016, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libgcc_s.so.1", 102400, 110592, 8192, 94208, 0, 0, 8192, 102400, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libXext.so.6.4.0", 69632, 86016, 8192, 61440, 0, 0, 8192, 69632, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0", 24576, 32768, 8192, 16384, 0, 0, 8192, 24576, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libXau.so.6.0.0", 20480, 24576, 8192, 12288, 0, 0, 8192, 20480, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28", 983040, 1961984, 63488, 925696, 0, 0, 57344, 983040, 57344, 0], ["/usr/lib/x86_64-linux-gnu/libXi.so.6.1.0", 61440, 73728, 8192, 53248, 0, 0, 8192, 61440, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0", 118784, 172032, 8192, 110592, 0, 0, 8192, 118784, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0", 184320, 1298432, 20480, 163840, 0, 0, 20480, 184320, 20480, 0], ["/usr/lib/x86_64-linux-gnu/libz.so.1.2.11", 90112, 114688, 8192, 81920, 0, 0, 8192, 90112, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libexpat.so.1.6.11", 94208, 188416, 13312, 81920, 0, 0, 12288, 94208, 12288, 0], ["/usr/lib/x86_64-linux-gnu/libm-2.31.so", 577536, 1372160, 16384, 569344, 0, 0, 8192, 577536, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libutil-2.31.so", 16384, 20480, 8192, 8192, 0, 0, 8192, 16384, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libdl-2.31.so", 20480, 24576, 8192, 12288, 0, 0, 8192, 20480, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libpthread-2.31.so", 102400, 126976, 8192, 94208, 0, 0, 8192, 102400, 8192, 0], ["/usr/lib/x86_64-linux-gnu/libc-2.31.so", 1540096, 2023424, 39936, 1515520, 0, 0, 24576, 1540096, 24576, 0], ["/usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4", 65536, 77824, 14336, 57344, 0, 0, 8192, 65536, 8192, 0], ["/usr/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so", 32768, 32768, 14336, 24576, 0, 0, 8192, 32768, 8192, 0], ["/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", 28672, 28672, 0, 28672, 0, 0, 0, 28672, 0, 0], ["/usr/local/lib/AppProtection/libAppProtection.so.22.11.0.2", 167936, 2281472, 9216, 159744, 0, 0, 8192, 167936, 8192, 0], ["/usr/lib/x86_64-linux-gnu/ld-2.31.so", 188416, 188416, 8192, 180224, 0, 0, 8192, 188416, 8192, 0], ["[stack]", 106496, 135168, 106496, 0, 0, 0, 106496, 106496, 106496, 0], ["[vvar]", 0, 16384, 0, 0, 0, 0, 0, 0, 0, 0], ["[vdso]", 4096, 8192, 0, 4096, 0, 0, 0, 4096, 0, 0], ["[vsyscall]", 0, 4096, 0, 0, 0, 0, 0, 0, 0, 0]], "create_time": 1681346443.08, "cpu_percent": 0.0, "username": "o54ma", "status": "running", "pid": 11269, "memory_full_info": [15659008, 28688384, 8802304, 2711552, 0, 7110656, 0, 6926336, 7573504, 0], "cpu_times": [0.06, 0.02, 0.0, 0.0, 0.0], "cmdline": ["python3", "test_psutil copy.py"], "ionice": [0, 0], "uids": [1000, 1000, 1000], "ppid": 6715, "io_counters": [241, 1, 0, 0, 1121794, 8], "open_files": [], "num_threads": 1, "memory_percent": 0.18083494950336423, "cpu_affinity": [0, 1, 2, 3, 4, 5, 6, 7], "num_fds": 4, "environ": {"COLORFGBG": "15;0", "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus", "DESKTOP_SESSION": "ubuntu", "DISPLAY": ":0", "GDMSESSION": "ubuntu", "GIO_LAUNCHED_DESKTOP_FILE_PID": "6707", "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated", "GNOME_SHELL_SESSION_MODE": "ubuntu", "GPG_AGENT_INFO": "/run/user/1000/gnupg/S.gpg-agent:0:1", "GTK_MODULES": "gail:atk-bridge", "HOME": "/home/o54ma", "IM_CONFIG_PHASE": "1", "INVOCATION_ID": "db5386f5998444018034001d35ecf227", "JOURNAL_STREAM": "8:74986", "LANG": "en_US.UTF-8", "LANGUAGE": "", "LC_ADDRESS": "en_US.UTF-8", "LC_IDENTIFICATION": "en_US.UTF-8", "LC_MEASUREMENT": "en_US.UTF-8", "LC_MONETARY": "en_US.UTF-8", "LC_NAME": "en_US.UTF-8", "LC_NUMERIC": "en_US.UTF-8", "LC_PAPER": "en_US.UTF-8", "LC_TELEPHONE": "en_US.UTF-8", "LC_TIME": "en_US.UTF-8", "LIBVIRT_DEFAULT_URI": "qemu:///system", "LOGNAME": "o54ma", "MANAGERPID": "3052", "PAPERSIZE": "letter", "PATH": "/home/o54ma/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "PT8HOME": "/opt/pt", "PWD": "/home/o54ma/Uni/GP/NOCD_Testing", "QT_ACCESSIBILITY": "1", "QT_IM_MODULE": "ibus", "SESSION_MANAGER": "local/IdeaPad-L3:@/tmp/.ICE-unix/3281,unix/IdeaPad-L3:/tmp/.ICE-unix/3281", "SHELL": "/usr/bin/zsh", "SHLVL": "1", "SSH_AGENT_PID": "3241", "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh", "TERM": "xterm-256color", "USER": "o54ma", "USERNAME": "o54ma", "WINDOWID": "0", "WINDOWPATH": "2", "XAUTHORITY": "/run/user/1000/gdm/Xauthority", "XDG_CONFIG_DIRS": "/etc/xdg/xdg-ubuntu:/etc/xdg", "XDG_CURRENT_DESKTOP": "ubuntu:GNOME", "XDG_DATA_DIRS": "/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop", "XDG_MENU_PREFIX": "gnome-", "XDG_RUNTIME_DIR": "/run/user/1000", "XDG_SESSION_CLASS": "user", "XDG_SESSION_DESKTOP": "ubuntu", "XDG_SESSION_TYPE": "x11", "XMODIFIERS": "@im=ibus", "_": "/usr/bin/python3", "OLDPWD": "/home/o54ma", "ZSH": "/home/o54ma/.oh-my-zsh", "PAGER": "less", "LESS": "-R", "LSCOLORS": "Gxfxcxdxbxegedabagacad", "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3= [...]

2023-04-14 20:55 UTC, OsamaMomani commented on src/network_sniffer/network_sniffer.py
I will have a look if I could put the psutil library into use. 
For now, SsHelper has better performance and memory efficiency, also, NOCD is primarily a Linux tool and isn't intended to be cross-platform.

2023-04-18 10:06 UTC, closed without merging